#curl titles
curl_titles=(
	"Basic GET at the website root"
	"POST to the /upload location"
	"DELETE from the /upload location"
	"POST to the root location"
	"DELETE nonexisting file"
	"DELETE from the root location"
	"DELETE a directory"
	"GET an autoindex of the /upload location"
	"GET a 301 redirection"
	"GET a 307 redirection"
	"GET a 308 redirection"
	"BREW a pot of coffee"
	"DELETE a non-empty directory"
	"GET with unsupported HTTP version"
	"POST with a malformed request"
	"POST without content-length"
	"GET on an infinite loop"
	"GET chapter 21 with Python CGI"
	"GET chapter 42 with bash CGI"
	"POST a file via Python CGI"
	"DELETE the testfile from the /upload location"
	"POST a file via Bash CGI"
	"DELETE the testfile from the /upload location again"
)

#curl tests
curl_tests=(
	"${httpPrefix}${serverAddr}:__PORT__"
	"-X POST -F \"file=@${testFile}\" ${httpPrefix}${serverAddr}:__PORT__/upload"
	"-X DELETE ${httpPrefix}${serverAddr}:__PORT__/upload/${testFileEncoded}"
	"-X POST -F \"file=@${testFile}\" ${httpPrefix}${serverAddr}:__PORT__"
	"-X DELETE ${httpPrefix}${serverAddr}:__PORT__/upload/${testFileEncoded}"
	"-X DELETE ${httpPrefix}${serverAddr}:__PORT__/${testFileEncoded}"
	"-X DELETE ${httpPrefix}${serverAddr}:__PORT__/${dir}"
	"${httpPrefix}${serverAddr}:__PORT__/upload"
	"${httpPrefix}${serverAddr}:__PORT__/redir"
	"${httpPrefix}${serverAddr}:__PORT__/temp_redir"
	"${httpPrefix}${serverAddr}:__PORT__/moved_permanently"
	"-X BREW ${httpPrefix}${serverAddr}:__PORT__"
	"-X DELETE ${httpPrefix}${serverAddr}:__PORT__/upload"
	"--http1.0 ${httpPrefix}${serverAddr}:__PORT__"
	"-X POST -H \"Content-Length: notanumber\" -F \"file=@${testFile}\" ${httpPrefix}${serverAddr}:__PORT__/upload"
	"-X POST ${httpPrefix}${serverAddr}:__PORT__/upload"
	"-L ${httpPrefix}${serverAddr}:__PORT__/loop"
	"${httpPrefix}${serverAddr}:__PORT__/cgi-bin/getCgi.py?chapter=21"
	"${httpPrefix}${serverAddr}:__PORT__/cgi-bin/getCgi.sh?chapter=42"
	"-X POST -F \"file=@${testFile}\" ${httpPrefix}${serverAddr}:__PORT__/cgi-bin/postCgi.py"
	"-X DELETE ${httpPrefix}${serverAddr}:__PORT__/upload/${testFileEncoded}"
	"-X POST -F \"file=@${testFile}\" ${httpPrefix}${serverAddr}:__PORT__/cgi-bin/postCgi.sh"
	"-X DELETE ${httpPrefix}${serverAddr}:__PORT__/upload/${testFileEncoded}"
)
