#netcat titles
netcat_titles=(
	"Basic GET at the website root"
	"POST to the /upload location"
	"DELETE from the /upload location"
	"POST to the root location"
	"DELETE nonexisting file"
	"DELETE from the root location"
	"DELETE a directory"
	"GET an autoindex of the /upload location"
	"GET a 301 redirection"
	"GET a 307 redirection"
	"GET a 308 redirection"
	"BREW a pot of coffee"
	"DELETE a non-empty directory"
	"GET with unsupported HTTP version"
	"POST with a malformed request"
	"POST without content-length"
	"GET on an infinite loop"
	"GET chapter 21 with Python CGI"
	"GET chapter 42 with bash CGI"
	"POST a file via Python CGI"
	"DELETE the testfile from the /upload location"
	"POST a file via Bash CGI"
	"DELETE the testfile from the /upload location again"
	"POST with chunked encoding CRLF to a non-allowed location"
	"POST with chunked encoding LF to a non-allowed location"
	"POST with chunked encoding CRLF to an allowed location"
	"POST with chunked encoding LF to an allowed location"
	"POST with chunked encoding, incorrect ending and CRLF"
	"POST with chunked encoding, incorrect ending and LF"
)

#netcat tests
netcat_tests=(
	"GET / HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\n\r\n"
	"${request_valid}"
	"DELETE /upload/${testFileEncoded} HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\n\r\n"
	"${request_invalid}"
	"DELETE /upload/${testFileEncoded} HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\n\r\n"
	"DELETE /${testFileEncoded} HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\n\r\n"
	"DELETE /${dir} HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\n\r\n"
	"GET /upload HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\n\r\n"
	"GET /redir HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\n\r\n"
	"GET /temp_redir HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\n\r\n"
	"GET /moved_permanently HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\n\r\n"
	"BREW / HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\n\r\n"
	"DELETE /upload HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\n\r\n"
	"GET / HTTP/1.0\r\nHost: ${serverAddr}:__PORT__\r\n\r\n"
	"POST /upload HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\nContent-Length: notanumber\r\n\r\n"
	"POST /upload HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\n\r\n"
	"GET /loop HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\n\r\n"
	"GET /cgi-bin/getCgi.py?chapter=21 HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\n\r\n"
	"GET /cgi-bin/getCgi.sh?chapter=42 HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\n\r\n"
	"POST /cgi-bin/postCgi.py HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\nContent-Type: multipart/form-data; boundary=${boundary}\r\nContent-Length: ${content_length}\r\n\r\n${body}"
	"DELETE /upload/${testFileEncoded} HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\n\r\n"
	"POST /cgi-bin/postCgi.sh HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\nContent-Type: multipart/form-data; boundary=${boundary}\r\nContent-Length: ${content_length}\r\n\r\n${body}"
	"DELETE /upload/${testFileEncoded} HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\n\r\n"
	"POST / HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\nTransfer-Encoding: chunked\r\nContent-Type: text/plain\r\n\r\n4\r\nWiki\r\n5\r\npedia\r\nE\r\n in\r\n\r\nchunks.\r\n0\r\n\r\n"
	"POST / HTTP/1.1\nHost: ${serverAddr}:__PORT__\nTransfer-Encoding: chunked\nContent-Type: text/plain\n\n4\nWiki\n5\npedia\nC\n in\n\nchunks.\n0\n\n"
	"POST /upload HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\nTransfer-Encoding: chunked\r\nContent-Type: text/plain\r\n\r\n4\r\nWiki\r\n5\r\npedia\r\nE\r\n in\r\n\r\nchunks.\r\n0\r\n\r\n"
	"POST /upload HTTP/1.1\nHost: ${serverAddr}:__PORT__\nTransfer-Encoding: chunked\nContent-Type: text/plain\n\n4\nWiki\n5\npedia\nC\n in\n\nchunks.\n0\n\n"
	"POST / HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\nTransfer-Encoding: chunked\r\nContent-Type: text/plain\r\n\r\n4\r\nWiki\r\n5\r\npedia\r\nE\r\n in\r\n\r\nchunks.\r\n"
	"POST / HTTP/1.1\r\nHost: ${serverAddr}:__PORT__\r\nTransfer-Encoding: chunked\r\nContent-Type: text/plain\r\n\r\n4\nWiki\n5\npedia\nC\n in\n\nchunks.\n"
)
